// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBifjDmGSu6F39dULpHb95BR9xdx30Fwsc',
    appId: '1:517335807297:web:e9cee7a9e9ede9e2259dc0',
    messagingSenderId: '517335807297',
    projectId: 'smort-shopperdb',
    authDomain: 'smort-shopperdb.firebaseapp.com',
    storageBucket: 'smort-shopperdb.firebasestorage.app',
    measurementId: 'G-Z4TJYDRYKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxzhhjvWPvA-umVjuQK1gi2z4uS0s9BVw',
    appId: '1:517335807297:android:d10409e929684de6259dc0',
    messagingSenderId: '517335807297',
    projectId: 'smort-shopperdb',
    storageBucket: 'smort-shopperdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwtSukn2BMtujEGxlkg_Oa0cg8xLT2d8k',
    appId: '1:517335807297:ios:6efbe059915ace43259dc0',
    messagingSenderId: '517335807297',
    projectId: 'smort-shopperdb',
    storageBucket: 'smort-shopperdb.firebasestorage.app',
    iosClientId: '517335807297-jtdoa5grj95itduk1h3m0avn7s6oek7u.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwtSukn2BMtujEGxlkg_Oa0cg8xLT2d8k',
    appId: '1:517335807297:ios:6efbe059915ace43259dc0',
    messagingSenderId: '517335807297',
    projectId: 'smort-shopperdb',
    storageBucket: 'smort-shopperdb.firebasestorage.app',
    iosClientId: '517335807297-jtdoa5grj95itduk1h3m0avn7s6oek7u.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBifjDmGSu6F39dULpHb95BR9xdx30Fwsc',
    appId: '1:517335807297:web:56737e81893ae7bc259dc0',
    messagingSenderId: '517335807297',
    projectId: 'smort-shopperdb',
    authDomain: 'smort-shopperdb.firebaseapp.com',
    storageBucket: 'smort-shopperdb.firebasestorage.app',
    measurementId: 'G-N9E1ZY92NN',
  );

}