// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5XLwUM5855yeLblHh2r36eZy23Qmjs5c',
    appId: '1:653328168076:web:71f0596d51755c6459b7a9',
    messagingSenderId: '653328168076',
    projectId: 'grad-proj-cc2cd',
    authDomain: 'grad-proj-cc2cd.firebaseapp.com',
    storageBucket: 'grad-proj-cc2cd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCff5GXrLfYVjwhUgm-rs18fbPbLQJk_n4',
    appId: '1:653328168076:android:0f2701b07dd604e559b7a9',
    messagingSenderId: '653328168076',
    projectId: 'grad-proj-cc2cd',
    storageBucket: 'grad-proj-cc2cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs6MWkj0T-Hx-1yWvvoM0gGVCtlgN_BLw',
    appId: '1:653328168076:ios:b84825ace4b3399a59b7a9',
    messagingSenderId: '653328168076',
    projectId: 'grad-proj-cc2cd',
    storageBucket: 'grad-proj-cc2cd.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs6MWkj0T-Hx-1yWvvoM0gGVCtlgN_BLw',
    appId: '1:653328168076:ios:b84825ace4b3399a59b7a9',
    messagingSenderId: '653328168076',
    projectId: 'grad-proj-cc2cd',
    storageBucket: 'grad-proj-cc2cd.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5XLwUM5855yeLblHh2r36eZy23Qmjs5c',
    appId: '1:653328168076:web:7ee5d6c6501464cb59b7a9',
    messagingSenderId: '653328168076',
    projectId: 'grad-proj-cc2cd',
    authDomain: 'grad-proj-cc2cd.firebaseapp.com',
    storageBucket: 'grad-proj-cc2cd.firebasestorage.app',
  );
}
